### PR TITLE
Add Typescript typings

### LINKED ISSUE #1: TypeScript typings
It would be awesome if you could include typings for TypeScript either as part of this package (preferably) or alternatively as a [DT](https://github.com/DefinitelyTyped/DefinitelyTyped).

Thanks for providing an awesome NLP service!

### PR DESCRIPTION
**Pull request by juliensalinas**
Fixes #1

### CODE REVIEW

**Comment by lirbank** [comment]
This is great but the `any` type is not great. It basically disables type checking all together. But this is still much better than no types at all, since we can now use it with TS without writing our own type definitions.

For reference, are the type defs I wrote to be able to use nlpcloud-js with TS:

```ts
declare module "nlpcloud" {
  export default class NLPCloudClient {
    constructor(model: string, token: string, gpu: boolean = false) {}
    entities(text: string): Promise<{
      status: number;
      statusText: string;
      data: {
        entities: { start: number; end: number; type: string; text: string }[];
      };
    }>;
  }
}
```

As you can see, I only typed the part of the class that I needed. If you want to, you could copy over the `entities` method to your type defs. The typings above are more specific than the generated one which mostly rely on making all types `any`.

On another note, I think it would be dead simple to rewrite this lib in TS and then you'd never have to worry about TS types anymore. TS would output both JS and TS types, and they would always be in sync, and correct.

**Comment by lirbank** [comment]
You should also update your package.json with a `types` field, see: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by juliensalinas** [comment]
Thanks @lirbank , we will have a look ASAP!

**Comment by juliensalinas** [comment]
Hi @lirbank , we just finished implementing the types, the same way you did.
We also added the path to the types file to the `package.json`.
Does it look good? Or do you think we're still missing something important?

Thanks!

**Pull request merged**
